### ISSUE TITLE
Can we fix "Scroll bar width calculated incorrectly" issue from original BSL lib?

### ISSUE THREAD

**Issue by krutoo** [rick-liruixin/body-scroll-lock-upgrade#16]
Hi, i describe problem with original BSL library here:
https://github.com/willmcpo/body-scroll-lock/issues/239

Can we fix that algorithm in this body-scroll-lock-upgrade?

**Comment by ialse** [comment]
I'll add that the width needs to be calculated via getComputedStyle since it's different from clientWidth. Therefore, there is a small content shift.




That is, instead of

`const scrollBarGap = window.innerWidth - document.documentElement.clientWidth;`

need to
      
`const scrollBarGap =  window.innerWidth - document.documentElement.getBoundingClientRect().width`

As a rule, this gives a fractional number, due to which there is a minimum content shift

UPD:
Checked in Chrome, unfortunately did not work. The scroll width was calculated as 16.333, but a small shift still remained. Empirically, I calculated that the correct value is 16.666, then there is no shift. Apparently, there are some nuances of browser rendering

UPD2:

For myself, I solved the problem by setting the width of the scrollbar to exactly 16 px . Unfortunately, this is only possible for webkit browsers. But for this I had to redefine all the properties of the scrollbar:

https://stackoverflow.com/questions/9060421/css3-how-to-restore-webkit-scrollbar-property-to-the-default-scroll-bar

https://github.com/rick-liruixin/body-scroll-lock-upgrade/assets/66719870/8767d5a4-399b-45dc-9c66-dc23113aa5aa
      
![width](https://github.com/rick-liruixin/body-scroll-lock-upgrade/assets/66719870/e7809812-7231-45f4-acda-9ade30f8c530)

**Comment by rick-liruixin** [comment]
Yes, I will fix this feature in my recent free time @krutoo @ialse

**Comment by krutoo** [comment]
@rick-liruixin Don't you have time yet?

**Comment by rick-liruixin** [comment]
> @rick-liruixin Don't you have time yet?

Sorry, I've been too busy to update. It is now complete. @krutoo @ialse
